### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tony9664** [microsoft/AI2BMD#16]
I built a small dipeptide system and after equilibrium I got an error message:
```
Traceback (most recent call last):
  File "/ai2bmd/main.py", line 61, in <module>
    simulator.set_calculator(
  File "/ai2bmd/AIMD/simulator.py", line 68, in set_calculator
    self.initialize_fragcalc()
  File "/ai2bmd/AIMD/simulator.py", line 55, in initialize_fragcalc
    self.qmcalc.bonded_calculator.fragment_method.fragment(self.qmatoms)
  File "/ai2bmd/Fragmentation/distancefrag.py", line 147, in fragment
    residuenames[dipeptides_index[1][6]],
IndexError: list index out of range
``` 

This is the input pdb file
```
ATOM      1  H1  ACE     1       2.000   1.000  -0.000  1.00  0.00
ATOM      2  CH3 ACE     1       2.000   2.090   0.000  1.00  0.00
ATOM      3  H2  ACE     1       1.486   2.454   0.890  1.00  0.00
ATOM      4  H3  ACE     1       1.486   2.454  -0.890  1.00  0.00
ATOM      5  C   ACE     1       3.427   2.641  -0.000  1.00  0.00
ATOM      6  O   ACE     1       4.391   1.877  -0.000  1.00  0.00
ATOM      7  N   ALA     2       3.555   3.970  -0.000  1.00  0.00
ATOM      8  H   ALA     2       2.733   4.556  -0.000  1.00  0.00
ATOM      9  CA  ALA     2       4.853   4.614  -0.000  1.00  0.00
ATOM     10  HA  ALA     2       5.408   4.316   0.890  1.00  0.00
ATOM     11  CB  ALA     2       5.661   4.221  -1.232  1.00  0.00
ATOM     12  HB1 ALA     2       5.123   4.521  -2.131  1.00  0.00
ATOM     13  HB2 ALA     2       6.630   4.719  -1.206  1.00  0.00
ATOM     14  HB3 ALA     2       5.809   3.141  -1.241  1.00  0.00
ATOM     15  C   ALA     2       4.713   6.129   0.000  1.00  0.00
ATOM     16  O   ALA     2       3.601   6.653   0.000  1.00  0.00
ATOM     17  N   NME     3       5.846   6.835   0.000  1.00  0.00
ATOM     18  H   NME     3       6.737   6.359  -0.000  1.00  0.00
ATOM     19  CH3 NME     3       5.846   8.284   0.000  1.00  0.00
ATOM     20 HH31 NME     3       4.819   8.648   0.000  1.00  0.00
ATOM     21 HH32 NME     3       6.360   8.648   0.890  1.00  0.00
ATOM     22 HH33 NME     3       6.360   8.648  -0.890  1.00  0.00
END
```

**Comment by bi-ran** [comment]
you can use `--mode visnet` (and maybe `--gpus 0` on a multi-device machine`1) in this case to skip the fragmentation step and run on the system as a whole.

**Comment by tony9664** [comment]
Thank you it works now.
