### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 11.72 GiB total capacity; 9.61 GiB already allocated; 13.38 MiB free; 9.68 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by Lyueyang2020** [microsoft/AI2BMD#40]
Thank you for your excellent work! My base configuration is as follows.

> Ubuntu 22.04
> Docker version Version:24.0.7
> CPU 6 cores
> GPU 4070 SUPER

The example protein works very well and outputs the result chig-traj.traj. (ai2bmd --prot-file chig.pdb --preprocess-dir chig_preprocessed --preeq-steps 0 --sim-steps 10000 --record-per-steps 10 --gpus 0). 
I preprocessed a 200 residue protein (atomic number 31635 after adding water) with Amber22. When using ai2bmd the following error occurs, what could be the cause? Looking forward to your reply!

> Launching AI2BMD with Docker: docker run -w /mnt/home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161 --gpus '"device=0"' --rm -v /home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161:/mnt/home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161 -v /home/yueyang/program/AI2BMD-main2/src:/ai2bmd -v /home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161/sturcture/preprocessed:/mnt/home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161/sturcture/IBIIA_2bxd_preprocessed ghcr.io/microsoft/ai2bmd:latest python -u /ai2bmd/main.py --prot-file /mnt/home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161/sturcture/IBIIA_2bxd.pdb --base-dir /mnt/home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161 --log-dir /mnt/home/yueyang/work/4_AI2MD/3_rwf_12-10/3_rwf_161 --preeq-steps 0 --sim-steps 1000000 --timestep 2 --record-per-steps 5000 --constraints --device-strategy large-molecule --mm-method tinker-GPU
> DeviceStrategy: setting strategy to [large-molecule / combined]
> Preprocessing step already done, skip...
> run_preprocess takes 0.001737833023071289 seconds
> Loading models...
> Start simulation for 1000000 steps
> Traceback (most recent call last):
>   File "/ai2bmd/main.py", line 67, in <module>
>     simulator.simulate(
>   File "/ai2bmd/AIMD/simulator.py", line 188, in simulate
>     MolDyn.run(simulation_steps)
>   File "/opt/conda/lib/python3.9/site-packages/ase/md/md.py", line 137, in run
>     return Dynamics.run(self)
>   File "/opt/conda/lib/python3.9/site-packages/ase/optimize/optimize.py", line 156, in run
>     for converged in Dynamics.irun(self):
>   File "/opt/conda/lib/python3.9/site-packages/ase/optimize/optimize.py", line 122, in irun
>     self.atoms.get_forces()
>   File "/opt/conda/lib/python3.9/site-packages/ase/atoms.py", line 788, in get_forces
>     forces = self._calc.get_forces(self)
>   File "/opt/conda/lib/python3.9/site-packages/ase/calculators/abc.py", line 23, in get_forces
>     return self.get_property('forces', atoms)
>   File "/opt/conda/lib/python3.9/site-packages/ase/calculators/calculator.py", line 737, in get_property
>     self.calculate(atoms, [name], system_changes)
>   File "/ai2bmd/Calculators/qmmm.py", line 67, in calculate
>     qm_e, qm_f = qm.result()
>   File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
>     return self.__get_result()
>   File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
>     raise self._exception
>   File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/ai2bmd/Calculators/qmmm.py", line 26, in get_qmcalc_results
>     self.qmcalc.calculate(self.qmatoms, properties, system_changes)
>   File "/ai2bmd/Calculators/fragment.py", line 60, in calculate
>     energy, forces = zip(*execution_wrapper(f_args, self.concurrent))
>   File "/ai2bmd/utils/utils.py", line 242, in execution_wrapper
>     return [f.result() for f in futures]
>   File "/ai2bmd/utils/utils.py", line 242, in <listcomp>
>     return [f.result() for f in futures]
>   File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
>     return self.__get_result()
>   File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
>     raise self._exception
>   File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/ai2bmd/Calculators/bonded.py", line 109, in __call__
>     ) = self.calculate(fragments)
>   File "/ai2bmd/Calculators/bonded.py", line 82, in calculate
>     for item in zip(*[f.result() for f in futures])
>   File "/ai2bmd/Calculators/bonded.py", line 82, in <listcomp>
>     for item in zip(*[f.result() for f in futures])
>   File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
>     return self.__get_result()
>   File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
>     raise self._exception
>   File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/ai2bmd/Calculators/bonded.py", line 49, in _inference_impl
>     return zip(*[model.dl_potential_loader(unit) for unit in data])
>   File "/ai2bmd/Calculators/bonded.py", line 49, in <listcomp>
>     return zip(*[model.dl_potential_loader(unit) for unit in data])
>   File "/ai2bmd/Calculators/visnet_calculator.py", line 58, in dl_potential_loader
>     e, f = self.model(self.collate(frag_data))
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
>   File "/ai2bmd/ViSNet/model/visnet.py", line 139, in forward
>             data['pos'].requires_grad_(True)
>     
>         x, v = self.representation_model(data)
>                ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>         x = self.output_model.pre_reduce(x, v, data['z'], data['pos'], data['batch'])
>         x = x * self.std
>   File "/ai2bmd/ViSNet/model/visnet_block.py", line 126, in forward
>         # ViS-MP Layers
>         for attn in self.vis_mp_layers[:-1]:
>             dx, dvec, dedge_attr = attn.forward(
>                                    ~~~~~~~~~~~~ <--- HERE
>                 x, vec, edge_index, edge_weight, edge_attr, edge_vec
>             )
>   File "/tmp/root_pyg/tmpyb184bzz.py", line 355, in forward
>         v = self.v_proj(x).reshape(-1, self.num_heads, self.head_dim)
>         dk = self.act(self.dk_proj(f_ij)).reshape(-1, self.num_heads, self.head_dim)
>         dv = self.act(self.dv_proj(f_ij)).reshape(-1, self.num_heads, self.head_dim)
>              ~~~~~~~~ <--- HERE
>     
>         vec1, vec2, vec3 = torch.split(
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 391, in forward
>     def forward(self, input: Tensor) -> Tensor:
>         return F.silu(input, inplace=self.inplace)
>                ~~~~~~ <--- HERE
>   File "/opt/conda/lib/python3.9/site-packages/torch/nn/functional.py", line 2048, in silu
>     if inplace:
>         return torch._C._nn.silu_(input)
>     return torch._C._nn.silu(input)
>            ~~~~~~~~~~~~~~~~~ <--- HERE
> RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB (GPU 0; 11.72 GiB total capacity; 9.61 GiB already allocated; 13.38 MiB free; 9.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by bi-ran** [comment]
you can pass `--chunk-size <size>` (in units of atoms) to split the data into batches and reduce peak memory usage. note that this affects only the atoms of the protein.
