### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by thippo** [microsoft/AI2BMD#46]
(base) [root@ai_test src]# python main.py --prot-file chig.pdb --preprocess-dir chig_preprocessed --preeq-steps 0 --sim-steps 1000 --record-per-steps 1
Traceback (most recent call last):
  File "/root/AI2BMD/src/main.py", line 10, in <module>
    from AIMD.simulator import SolventSimulator, NoSolventSimulator
  File "/root/AI2BMD/src/AIMD/simulator.py", line 19, in <module>
    from Calculators.fragment import FragmentCalculator
  File "/root/AI2BMD/src/Calculators/fragment.py", line 4, in <module>
    from Calculators.bonded import DLBondedCalculator
  File "/root/AI2BMD/src/Calculators/bonded.py", line 15, in <module>
    from Fragmentation import DistanceFragment
  File "/root/AI2BMD/src/Fragmentation/__init__.py", line 1, in <module>
    from .distancefrag import DistanceFragment
  File "/root/AI2BMD/src/Fragmentation/distancefrag.py", line 17, in <module>
    from Fragmentation.hydrogen import CTable, HydrogenOptimizer, ProteinData, ProteinDataBatch
  File "/root/AI2BMD/src/Fragmentation/hydrogen/__init__.py", line 2, in <module>
    from .energies import HydrogenOptimizer
  File "/root/AI2BMD/src/Fragmentation/hydrogen/energies.py", line 5, in <module>
    from Fragmentation.hydrogen.topology import ProteinData
  File "/root/AI2BMD/src/Fragmentation/hydrogen/topology.py", line 133, in <module>
    class ProteinDataBatch(Batch, ProteinData):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Is there same thing wrong with python code about subclass？

**Comment by bi-ran** [comment]
how are you running the code? we cannot reproduce this error in the docker container we provide

**Comment by thippo** [comment]
> how are you running the code? we cannot reproduce this error in the docker container we provide

Yes, It work in the docker container.

But when I run the src code, this error happend, because I want to do some secondary development.

**Comment by bi-ran** [comment]
you can pass --src-dir /path/to/local/src/directory/ to the script to mount your local src directory with your changes. the error is likely due to incompatible package versions
